# config.yaml
detectors:
- name: regex password
  keywords:
  - PASSWORD
  - TOKEN
  - PASS
  - password
  - pass
  regex:
    adjective: (\S+)PASSWORD(\S+)
  regex:
    id: id-[a-zA-Z0-9]{16}
    secret: [a-zA-Z0-9]{32}


