# config.yaml
detectors:
- name: detector regex
  keywords:
  - PASSWORD
  - TOKEN
  - PASS
- name: regex1
  regex:
    adjective: (\S+)PASSWORD(\S+)
- name: regex2
  regex:
    adjective: (\S+)TOKEN(\S+)
- name: regex3
  regex:
    adjective: (\S+)PASS(\S+)
