# config.yaml
detectors:
 - keywords:
  - PASSWORD
  - TOKEN
  - PASS
  - password
  - pass
  name: regex 1
  regex:
    adjective: (\S+)PASSWORD(\S+)
  name: regex 2
  regex:
    id: id-[a-zA-Z0-9]{16}
    secret: '[a-zA-Z0-9]{32}'


