# config.yaml
detectors:
- name: detector regex
  keywords:
  - PASSWORD
  - TOKEN
  - PASS
  regex:
    adjective: (\S+)PASSWORD(\S+)
  regex:
    adjective: (\S+)TOKEN(\S+)
  regex:
    adjective: (\S+)PASS(\S+)
  regex:
    id: id-[a-zA-Z0-9]{16}
    secret: [a-zA-Z0-9]{32}


